server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy para o serviço de estoque
    location /api/estoque/ {
        proxy_pass http://estoque:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para o serviço de faturamento
    location /api/faturamento/ {
        proxy_pass http://faturamento:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Suporte ao roteamento SPA do Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}
